### ISSUE TITLE
Website CSS issue when HN post contains preformatted code

### ISSUE THREAD

**Issue by hongshaoyang** [algolia/hn-search#226]
1. Search for [Show HN: HN Avatars in 357 bytes](https://news.ycombinator.com/item?id=30668137) on desktop
2. Scroll to the right
3. Preformatted code doesn't wrap properly:
<img width="1257" alt="Screenshot 2022-03-20 at 12 46 57 PM" src="https://user-images.githubusercontent.com/19281800/159150484-707082fc-bce8-43bb-bcc7-b08fe85ac3b9.png">

# suggested solution
- the `Story_data` class is a flexbox that is taking taking up width when a `code, pre` node is present. set a maxwidth on `Story_data`
- Set `code, pre` to `overflow: scroll`

```css
.Story_data {
  flex: auto;
  max-width: 50%;
}

code, pre {
  overflow: scroll;
}

.experimental .Story_share {
  /* flex: 1 1; */
  flex: 140px;
}
```
